inherit_from:
  - .rubocop_airbnb.yml

RSpec/ExpectChange:
  EnforcedStyle: block

#以下にはrubocopで検証したくないフォルダを指定する
AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
